### ISSUE TITLE
Error running the command, related to latex2svg.py

### ISSUE THREAD

**Issue by jjnilton** [phseiff/github-flavored-markdown-to-html#39]
Hi, thanks for sharing this software!

However, I'm not able to run it, even running just `gh-md-to-html` or `gh-md-to-html -d` gives an error. I'm using the version `gh-md-to-html-1.11.6` and `Python 3.9.2` on `Debian Bullseye`.

```
Traceback (most recent call last):
  File "/home/jj/.local/lib/python3.9/site-packages/gh_md_to_html/latex2svg.py", line 101, in latex2svg
    ret.check_returncode()
  File "/usr/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['latex', '-interaction', 'nonstopmode', '-halt-on-error', 'code.tex']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/jj/.local/lib/python3.9/site-packages/gh_md_to_html/__init__.py", line 1, in <module>
    from .__main__ import *
  File "/home/jj/.local/lib/python3.9/site-packages/gh_md_to_html/__main__.py", line 247, in <module>
    raw_formula2svg_offline("w")
  File "/home/jj/.local/lib/python3.9/site-packages/gh_md_to_html/__main__.py", line 236, in raw_formula2svg_offline
    return latex2svg(formula)["svg"]
  File "/home/jj/.local/lib/python3.9/site-packages/gh_md_to_html/latex2svg.py", line 84, in latex2svg
    return latex2svg(code, params, working_directory=tmpdir)
  File "/home/jj/.local/lib/python3.9/site-packages/gh_md_to_html/latex2svg.py", line 103, in latex2svg
    raise Exception("LaTeX failed with error:", str(ret.stderr, encoding="UTF-8"),
Exception: ('LaTeX failed with error:', '', '\nThis happened whilst rendering formula $w$.')
```

**Comment by phseiff** [comment]
Hi! Thanks for sharing this issue, I'm taking a look at it right now.

So every time you tun this command, even if it's just `gh-md-to-html -h`, you get this error? Ir is it just whenever you try to convert a markdown file?

**Comment by phseiff** [comment]
Does this happen with every markdown file, or just one specific one? Did you try running it on a semi-empty file, with nothing but e.g. "`foo`" inside?

**Comment by jjnilton** [comment]
Yes, it happens even when using `gh-md-to-html` without any options. It seems to happen with any markdown file too:

```
j@jj-mpc:~/Downloads$ echo "foo" > test.md
jj@jj-mpc:~/Downloads$ gh-md-to-html test.md 
Traceback (most recent call last):
  File "/home/jj/.local/lib/python3.9/site-packages/gh_md_to_html/latex2svg.py", line 101, in latex2svg
    ret.check_returncode()
  File "/usr/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['latex', '-interaction', 'nonstopmode', '-halt-on-error', 'code.tex']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:
[...]
```

**Comment by phseiff** [comment]
Okay, I think I found the problem:

What happens is that `gh-md-to-html` always checks whether `LaTeX` is installed or not, to see whether it should use the local installation of `LaTeX` or an online conversion tool to embed LaTeX formulas into the document (which probably isn't even relevant to you if you don't have any formulas within your document).

It does this by testing out whether LaTeX conversion works, and by then catching the error and processing it.
The mistake I made was that I forgot to properly catch some errors that `latex2svg.py` raises, causing `gh-md-to-html` to crash on some devices without a compatible LaTeX installation.

---

This issue should be fixed now; could you try updating to `v1.11.7` (via `pip3 install --upgrade gh-md-to-html>=1.11.7`) and see if the issue is fixed?

**Comment by jjnilton** [comment]
It works now, the error is gone. I still see a warning, though:

```
$ gh-md-to-html 
/usr/lib/python3.9/runpy.py:127: RuntimeWarning: 'gh_md_to_html.__main__' found in sys.modules after import of package 'gh_md_to_html', but prior to execution of 'gh_md_to_html.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
``` 

But the conversion works. Thanks for the explanation!

**Comment by phseiff** [comment]
The warning has been bugging me for a long time now, but I haven't managed to get rid of it, unfortunately.
It's related to how `gh-md-to-html` is a Python module run by a script wrapper, I think; though I should probably try to re-look into it eventually.

> Thanks for the explanation!
You're welcome :)

**Comment by phseiff** [comment]
@jjnilton 
Hello,
> It works now, the error is gone. I still see a warning, though:

I know it probably isn't even relevant to you anymore, but the warning you mentioned should be gone now, if you update to `v1.11.11` (via `pip3 install --upgrade gh-md-to-html>=1.11.11`).

**Comment by jjnilton** [comment]
Nice! Thanks for letting me know.
